services:
  backend:
    image: cabreraevil/nextjs-template:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-template
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - template_net

networks:
  template_net:
    name: template_net
