name: Deploy Production

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master

jobs:
  set_stage:
    name: Set Stage
    runs-on: ubuntu-latest
    outputs:
      stage: ${{ steps.set_stage.outputs.stage }}
    steps:
      - name: Set deployment stage
        id: set_stage
        run: |-
          case "${GITHUB_REF}" in
            refs/heads/master)
              echo "stage=production" >> $GITHUB_OUTPUT ;;
            *)
              echo "stage=preview" >> $GITHUB_OUTPUT ;;
          esac

  deploy:
    name: Deploy
    needs: [set_stage]
    uses: cabrera-evil/workflows/.github/workflows/deploy-vercel.yaml@master
    with:
      STAGE: ${{ needs.set_stage.outputs.stage }}
      VERCEL_TOKEN_REF: op://Vercel/cabrera-evil/token
      VERCEL_ORG_ID_REF: op://Vercel/cabrera-evil/organization-id
      VERCEL_PROJECT_ID_REF: op://Vercel/${{ github.event.repository.name }}/project-id
    secrets: inherit

  notify:
    name: Notify
    needs: deploy
    if: always()
    uses: cabrera-evil/workflows/.github/workflows/notify-status-discord.yaml@master
    with:
      DISCORD_WEBHOOK_REF: op://actions/Discord/webhook
    secrets: inherit
